name: petpaladmin

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  go_router: ^14.2.1
  url_strategy: ^0.2.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  firebase_core: ^3.2.0
  equatable: ^2.0.5
  font_awesome_flutter: ^10.7.0
  path: ^1.9.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0




flutter:


  uses-material-design: true
